[build]
builder = "nixpacks"
watchPatterns = ["chatbot_api.py", "requirements.txt", "saved_model/**"]

[deploy]
startCommand = "python chatbot_api.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
